name: builder-releaser

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build-test-vet-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Build
        run: go build -v ./...
      -
        name: Test
        run: go test -v ./...
      -
        name: Vet
        run: go vet -v ./...
      -
        name: BUILD FOR SNAP
        run: go build -v -mod=vendor
      # -
      #   name: DUMP DIR
      #   run: |
      #     echo $USER
      #     pwd
      #     ls -al
      # -
      #   name: Upload flightsim artifacts
      #   uses: actions/upload-artifact@v2
      #   # Upload the flightsim executable only to bin/ (bin will be created)
      #   with:
      #     name: bin
      #     path: ./flightsim
      -
        name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      -
        name: Save snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
      -
        name: Test snap
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          flightsim -h
      -
        if: startsWith(github.ref, 'refs/tags/v') == true
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      -
        if: startsWith(github.ref, 'refs/tags/v') == true
        name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
